package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	source := flag.String("source", "", "directory containing wake sound WAV files")
	output := flag.String("output", "", "generated Go output file")
	flag.Parse()
	if *source == "" || *output == "" {
		panic("-source and -output are required")
	}
	files, err := filepath.Glob(filepath.Join(*source, "*.wav"))
	if err != nil || len(files) == 0 {
		panic(fmt.Sprintf("find wake sounds: %v", err))
	}
	sort.Strings(files)
	var generated strings.Builder
	generated.WriteString("// Code generated by tools/embed_wake_sounds; DO NOT EDIT.\n\n")
	generated.WriteString("package taternative\n\n")
	generated.WriteString("var embeddedWakeSoundsGzipBase64 = map[string]string{\n")
	for _, path := range files {
		raw, err := os.ReadFile(path)
		if err != nil {
			panic(err)
		}
		var compressed bytes.Buffer
		writer, _ := gzip.NewWriterLevel(&compressed, gzip.BestCompression)
		writer.Header.Name = ""
		if _, err := writer.Write(raw); err != nil {
			panic(err)
		}
		if err := writer.Close(); err != nil {
			panic(err)
		}
		id := strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))
		fmt.Fprintf(&generated, "\t%q: %q,\n", id, base64.StdEncoding.EncodeToString(compressed.Bytes()))
	}
	generated.WriteString("}\n")
	formatted, err := format.Source([]byte(generated.String()))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		panic(err)
	}
}
